POST http://localhost:4002/products
content-type: application/json

{
    "name": "Caderno 96 Folhas",
    "price": 3
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/7496a9aa-4b5a-4ee5-8b0d-eae9e47f4621
