POST http://localhost:4002/products
content-type: application/json

{
    "name": "Caderno 96 Folhas",
    "price": 10
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/7496a9aa-4b5a-4ee5-8b0d-eae9e47f4621

###
PUT http://localhost:4002/products/ad847cbc-bc32-434a-af57-75d0a5318e45
content-type: application/json

{
    "name": "Caderno 96 Folhas Capa Azul",
    "price": 10
}

###

DELETE http://localhost:4002/products/8ebc3e26-d67e-4a91-825d-610f16ffc73e
